### ISSUE TITLE
【开源自荐】DBER：数据库ER图设计工具

### ISSUE THREAD

**Issue by findyourmagic** [ruanyf/weekly#2501]
## Repository

https://github.com/findyourmagic/dber/

## 主要功能

1. 可视化数据库结构设计
1. 拖拽生成模型引用关系
1. 一键导出SQL语句

## 演示动画

![DEMO](https://github.com/findyourmagic/dber/raw/master/dber.gif)

**Comment by cnazev** [comment]
@findyourmagic New graph 用不了 
试了下edge，fiefox，chrome浏览器 报错

**Comment by findyourmagic** [comment]
> @findyourmagic New graph 用不了 试了下edge，fiefox，chrome浏览器 报错如下：
> 
> { "_e": {}, "name": "DataCloneError", "message": "Failed to execute 'add' on 'IDBObjectStore': PointerEvent object could not be cloned.\n DataCloneError: Failed to execute 'add' on 'IDBObjectStore': PointerEvent object could not be cloned.", "inner": { "stack": "Error: Failed to execute 'add' on 'IDBObjectStore': PointerEvent object could not be cloned.\n at [https://dber.tech/_next/static/chunks/240-ad8144ea7a4eafa0.js:1:316209\n](https://dber.tech/_next/static/chunks/240-ad8144ea7a4eafa0.js:1:316209%5Cn) at Re ([https://dber.tech/_next/static/chunks/240-ad8144ea7a4eafa0.js:1:283272)\n](https://dber.tech/_next/static/chunks/240-ad8144ea7a4eafa0.js:1:283272)%5Cn) at new Ae ([https://dber.tech/_next/static/chunks/240-ad8144ea7a4eafa0.js:1:282768)\n](https://dber.tech/_next/static/chunks/240-ad8144ea7a4eafa0.js:1:282768)%5Cn) at Object.mutate ([https://dber.tech/_next/static/chunks/240-ad8144ea7a4eafa0.js:1:315484)\n](https://dber.tech/_next/static/chunks/240-ad8144ea7a4eafa0.js:1:315484)%5Cn) at Object.mutate ([https://dber.tech/_next/static/chunks/240-ad8144ea7a4eafa0.js:1:331174)\n](https://dber.tech/_next/static/chunks/240-ad8144ea7a4eafa0.js:1:331174)%5Cn) at Object.mutate ([https://dber.tech/_next/static/chunks/240-ad8144ea7a4eafa0.js:1:333253)\n](https://dber.tech/_next/static/chunks/240-ad8144ea7a4eafa0.js:1:333253)%5Cn) at Object.mutate ([https://dber.tech/_next/static/chunks/240-ad8144ea7a4eafa0.js:1:329033)\n](https://dber.tech/_next/static/chunks/240-ad8144ea7a4eafa0.js:1:329033)%5Cn) at [https://dber.tech/_next/static/chunks/240-ad8144ea7a4eafa0.js:1:294032\n](https://dber.tech/_next/static/chunks/240-ad8144ea7a4eafa0.js:1:294032%5Cn) at i ([https://dber.tech/_next/static/chunks/240-ad8144ea7a4eafa0.js:1:291727)\n](https://dber.tech/_next/static/chunks/240-ad8144ea7a4eafa0.js:1:291727)%5Cn) at https://dber.tech/_next/static/chunks/240-ad8144ea7a4eafa0.js:1:290715" } }

Thanks，这个问题已经修复了，在这里提 issue 可能关注不到，如果还有需要反馈的请到项目 repo 里发 issue.
